### ISSUE TITLE
This Week Milestone

### ISSUE THREAD

**Issue by ankurshukla03** [ankurshukla03/ldsaproject#1]
@santhoshnagav
- [x] Choose a dataset(we already did it but still just to be sure)
- [x] Make Objectives for this and next week
- [x] Find way how to download data and handles big amount of data using instance
- [x] What preprocessing we need to do with the dataset(data is already preprocessed)

TODO : Feel free to add if you feel like adding something more

**Comment by ankurshukla03** [comment]
@santhoshnagav remember to mail the project plan to andreas and also only send him the two csv files crime and library one so if we want to do more we can do that on our own but better not to write all that in project plan
- [ ] Mail the project plan to andreas
- [ ] add the link to project plan for the csv file which you feel like doing and write what you want to extract from that data
